name: 'SBOM Uploader'
description: 'Generates and uploads SBOM'
author: 'Neo'
inputs:
  scan_types:
    description: "Comma-separated list of scan types (e.g. secrets, sca, configs)"
    required: false
    default: "sca"
  # failure_level:
  #   description: "Severity levels to fail on (e.g. CRITICAL,HIGH,MEDIUM,ALL)"
  #   required: false
  #   default: "CRITICAL"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
